import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('94.141.98.224', username='root', password='25ELkJTNxhwCC7vF', timeout=15)
sftp = ssh.open_sftp()
with sftp.open('/opt/hairos-bot/fix_data.py', 'w') as f:
    f.write("import sqlite3\n")
    f.write("db = sqlite3.connect('bot_cache.db')\n")
    f.write("cur = db.cursor()\n")
    f.write("# 1. Restore Khrustina phone\n")
    f.write("cur.execute(\"UPDATE masters SET phone='+375295949109' WHERE name='Кристина'\")\n")
    f.write("print(f'Кристина phone: {cur.rowcount}')\n")
    f.write("# 2. Fix Marina specialization\n")
    f.write("cur.execute(\"UPDATE masters SET specialization='Капсульное/Голливудское наращивание, Трихопигментация SMP, Обучение' WHERE name='Марина'\")\n")
    f.write("print(f'Марина spec: {cur.rowcount}')\n")
    f.write("db.commit()\n")
    f.write("# Verify\n")
    f.write("cur.execute('SELECT id, name, phone, specialization, categories FROM masters')\n")
    f.write("for r in cur.fetchall(): print(r)\n")
    f.write("db.close()\n")
sftp.close()
stdin, stdout, stderr = ssh.exec_command('cd /opt/hairos-bot && source venv/bin/activate && python3 fix_data.py 2>&1')
print(stdout.read().decode())
stdin, stdout, stderr = ssh.exec_command('systemctl restart hairos-polling')
stdout.channel.recv_exit_status()
print('Done!')
ssh.close()
